name: Build PHP Binaries

on:
 push:
 workflow_dispatch:

jobs: 
  android:
    name: Android (PM 5)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
         repository: NetherGamesMC/php-build-scripts
         path: php-build-scripts
         ref: php/8.2
        
      - name: Install tools and dependencies
        run: |
          sudo apt update &> /dev/null
          sudo apt install -y re2c libtool libtool-bin zlib1g-dev libcurl4-openssl-dev libxml2-dev libyaml-dev libgmp-dev libzip-dev libssl-dev &> /dev/null
          
      - name: Making aarch64 php
        working-directory: php-build-scripts
        run: ./compile.sh -t linux64 -j14 -P5 -g

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: |
            ./php-build-scripts/bin/php7/bin/php
            ./php-build-scripts/bin/php7/bin/php.ini
          title: Latest PHP
          automatic_release_tag: "latest"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
