on:
  push:
  workflow_dispatch:

name: Release Binary For Android

jobs:
  build-php:
    name: Building cross compiler for android-aarch64
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      
    steps:
      - name: Init directories
        run: mkdir -p aarch64-linux-musl
      - name: Fetch aarch64-linux-musl from github release
        working-directory: aarch64-linux-musl
        run: wget -q -O "aarch64-linux-musl.tar.xz" "https://github.com/DaisukeDaisuke/musl-cross-make/releases/latest/download/aarch64-linux-musl.tar.xz"
        
      - name: Unzip aarch64-linux-musl
        working-directory: aarch64-linux-musl
        run: |
         tar Jxfv aarch64-linux-musl.tar.xz
         echo "$(pwd)/bin" >> $GITHUB_PATH
          
      - uses: actions/checkout@v4
        with:
         repository: pmmp/PHP-Binaries
         path: php-build-scripts
         ref: php/8.2

      - name: Install tools and dependencies
        run: |
          sudo apt update &> /dev/null
          sudo apt install -y re2c libtool libtool-bin zlib1g-dev libcurl4-openssl-dev libxml2-dev libyaml-dev libgmp-dev libzip-dev libssl-dev &> /dev/null
          
      - name: Making android-aarch64 php
        working-directory: php-build-scripts
        run: ./compile.sh -t android-aarch64 -x -j14 -P5 -g

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: |
            ./php-build-scripts/bin/php7/bin/php
            ./php-build-scripts/bin/php7/bin/php.ini
          title: Latest PHP
          automatic_release_tag: "latest"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
