name: 'Clean up stale PRs'

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          days-before-pr-stale: 14
          days-before-pr-close: 28
          remove-stale-when-updated: true
          exempt-all-assignees: true
          stale-pr-message: |
            This PR has been marked as "Stale", because there isn't any activity in the last 2 weeks.

            If there is no further activity, it will be closed in 28 days.

            Note for maintainers: Adding an assignee to the PR will prevent it from being marked as stale.
          close-pr-message: |
            As this PR hasn't been updated for a while, unfortunately we'll have to close it.
