name: Verify release artifacts

on:
  workflow_dispatch:
  workflow_run:
   workflows: [Auto trigger release]
   types: [completed]

jobs:
  verify-artifacts:
    # Only run if:
    # 1. The Auto trigger release workflow completed successfully
    # 2. The run-build job was executed (new_release was true)
    if: |
     github.event.workflow_run.conclusion == 'success' &&
     fromJson(github.event.workflow_run.jobs).jobs[?(@.name == 'run-build')].conclusion == 'success'
    
    name: Verify Security
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.1

      - name: Download assets
        run: |
          gh release download --repo "ItzxDwi/AndroidPHP" \
            --pattern 'php*' \
            --pattern 'checksums.*' \
            --clobber
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Verify Cosign signature
        run: |
          cosign verify-blob \
           --signature checksums.sig \
           --certificate checksums.pem \
           --certificate-identity-regexp "https://github.com/ItzxDwi/AndroidPHP" \
           --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
           checksums.sha256

      - name: Verify checksums
        run: sha256sum -c checksums.sha256
