name: Verify release artifacts

on:
  release:
    types: [published]
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., pm5-latest)"
        required: false
        default: "pm5-latest"

jobs:
  verify-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: sigstore/cosign-installer@v3.9.1

      - name: Get release tag
        id: release
        run: |
          TAG=${{ github.event_name == 'release' && github.event.release.tag_name || inputs.tag }}
          echo "tag=pm5-latest" >> $GITHUB_OUTPUT

      - name: Download assets
        run: |
          gh release download ${{ steps.release.outputs.tag }} \
            --pattern 'php*' \
            --pattern 'checksums.*' \
            --clobber
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Verify signature
        run: cosign verify-blob --signature checksums.sig --certificate checksums.pem checksums.sha256

      - name: Verify checksums
        run: sha256sum -c checksums.sha256
