name: Verify release artifacts

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., pm5-latest)"
        required: false
        default: "pm5-latest"

jobs:
  verify-artifacts:
    name: Verify Security
    runs-on: ubuntu-latest
    steps:

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.1

      - name: Get release tag
        id: release
        run: |
          TAG=${{ github.event_name == 'release' && github.event.release.tag_name || inputs.tag }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download assets
        run: |
          gh release download ${{ steps.release.outputs.tag }} \
            --repo "ItzxDwi/AndroidPHP" \
            --pattern 'php*' \
            --pattern 'checksums.*' \
            --clobber
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Verify Cosign signature
        run: |
          cosign verify-blob \
           --signature checksums.sig \
           --certificate checksums.pem \
           --certificate-identity-regexp "https://github.com/ItzxDwi/AndroidPHP" \
           --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
           checksums.sha256

      - name: Verify checksums
        run: sha256sum -c checksums.sha256
